API_KEY = ""
RATE = 16000 # Audio sampling rate
CHANNELS = 1
CHUNK = 1024
FORMAT = 8  #
DURATION = 8 # length of sound(s)
MODEL_SIZE = "small" #"base" #"tiny"
EMBEDDING_MODEL = "models/gemini-embedding-001"
CONTENT_GEN_MODEL = "models/gemini-2.0-flash"